Make the timestamp more robust against value format
Summary:
Use float instead of int to make timestamp be more robust. Below
shows ValueError when the client sends in a float number

>>> int('183488343.3438394')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '183488343.3438394'